apiVersion: batch/v1
kind: Job
metadata:
  name: job-6
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-6
        topology: jobs-tp
        scheduleTimeoutSeconds: "30"
        complete-depends-on: job-4__job-5
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-6
        image: bash
        command: ["bash", "-c", "echo Started: $(date) && sleep 10 && echo Ended: $(date)"]
      restartPolicy: Never
  backoffLimit: 3