apiVersion: batch/v1
kind: Job
metadata:
  name: job-2
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-2
        topology: jobs-tp
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-2
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"]
      restartPolicy: Never
  backoffLimit: 3