apiVersion: batch/v1
kind: Job
metadata:
  name: job-5
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-5
        topology: jobs-tp
        scheduleTimeoutSeconds: "90"
        complete-depends-on: job-3
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-5
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"]
      restartPolicy: Never
  backoffLimit: 3