apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-1
        topology: jobs-tp
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-1
        image: bash
        command: ["bash", "-c", "echo Started: $(date) && sleep 10 && echo Ended: $(date)"]
      restartPolicy: Never
  backoffLimit: 3
