apiVersion: batch/v1
kind: Job
metadata:
  name: job-5
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-5
        topology: jobs-tp
        scheduleTimeoutSeconds: "30"
        complete-depends-on: job-3
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-5
        image: bash
        command: ["bash", "-c", "echo Started: $(date) && sleep 60 && echo Ended: $(date)"]
      restartPolicy: Never
  backoffLimit: 3