apiVersion: batch/v1
kind: Job
metadata:
  name: job-4
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-4
        topology: jobs-tp
        complete-depends-off: job-4
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-4
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"]
      restartPolicy: Never
  backoffLimit: 3