apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-3
  labels:
    app: api-3
spec:
  selector:
    matchLabels:
      app: api-3
  template:
    metadata:
      labels:
        app: api-3
        topology: services-tp
        dependendency-off: frontend
        topology: topology-test
    spec:
      schedulerName: scheduler-framework-sample
      containers:
        - name: api-3
          image: vladalv/http-server:v1
          ports:
            - containerPort: 8080
