apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1
  labels:
    app: frontend-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-1
  template:
    metadata:
      labels:
        app: frontend-1
        topology: services-tp
        depends-on: backend__backend
        scheduleTimeoutSeconds: "30"
    spec:
      schedulerName: scheduler-framework-sample
      containers:
        - name: frontend-1
          image: vladalv/http-server:v1
          ports:
            - containerPort: 8080
