apiVersion: batch/v1
kind: Job
metadata:
  name: job-3
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      labels:
        app: job-3
        topology: services-tp
    spec:
      schedulerName: scheduler-framework-sample
      containers:
      - name: job-3
        image: bash
        command: ["bash", "-c", "echo Started: $(date) && sleep 60 && echo Ended: $(date)"]
      restartPolicy: Never
  backoffLimit: 3
