apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: web
  template:
    metadata:
      labels:
        app: backend
        tier: web
    spec:
      schedulerName: scheduler-framework-sample
      containers:
        - name: backend
          image: vladalv/http-server:v1
          ports:
            - containerPort: 8080
